package core.event;

public enum MType {
    ID_DEVICE_DATA,
    ID_ALARM_CHECK_TIMER_START,
    ID_ALARM_CHECK_TIMER_STOP,
    ID_DATA_CHECK_TIMER_START,
    ID_DATA_CHECK_TIMER_STOP,
    ID_UPDATE_DATA,
    ID_CHECK_DEVICE_STATUS,
}
