package core.event;

public enum MType {
    ID_UPDATE_DEVICE_DATA,
    ID_START_ALARM_CHECK_TIMER,
    ID_ALARM_CHECK_TIMER_STOP,
    ID_START_DATA_CHECK_TIMER,
    ID_DATA_CHECK_TIMER_STOP,
    ID_START_UPDATE_GUI_TIMER,
    ID_UPDATE_GUI,
    ID_CHECK_DEVICE_STATUS,
}
